### ISSUE TITLE
开发一个类似影音坊的APP，还要做哪些事

### ISSUE THREAD

**Issue by ar-world** [yangfeng1994/FFmpeg-Android#3]
大佬，想问下，我想用你这个FFmpeg-Android库，但是我看demo的配置参数太简单了，如果我想开发一个类似影音坊的APP，还要做哪些事呢？  除了用安卓控件做一个漂亮的UI，还需要用到OpenGLES去做渲染吗？

**Comment by yangfeng1994** [comment]
不需要的，很多FFmpeg的命令行我没有写在demo里面
